### ISSUE TITLE
determine whether cutoffs should be adjusted based on setx

### ISSUE THREAD

**Issue by sansamcl** [SansamLab/CRISPRScreenAnalysis#1]
- [x] look at setx beta score and fdr
- [x] make a new list of hits using setx beta score and fdr
- [x] decide whether this makes sense for enhancers and/or suppressors

**Comment by kevinboyd76** [comment]
I made 3 different lists. The first is all the hits within the SETX FDR range and had an absolute difference >0.5 . The second list is all the enhancers that are in that same SETX FDR range. The final list is all the enhancers that have a difference < -0.5 with no FDR cutoff.
